### ISSUE TITLE
Inverted QR code is not supported ?

### ISSUE THREAD

**Issue by SOAPEOPLE-HoussemAbdelkabir** [id1945/ngx-scanner-qrcode#72] opened 2024-08-12 20:57 UTC
The library doesn't work when I try to scan an inverted qr code (white qr code on black background)

**Comment by timeens** [comment] 2024-10-26 09:37
Duplicate of https://github.com/id1945/ngx-scanner-qrcode/issues/63#issue-2278955703

**Closed** 2024-11-24 10:30 UTC
